project:
  type: book
  output-dir: docs

book:
  title: "Libro de Consultas"
  subtitle: "Tendencias electorales (varias encuestas)"
  author: "Unidad de Análisis y Estudios"
  chapters:
    - index.qmd
    - part: "1 · Intención de voto"
      chapters:
        - 01_idv.qmd
        - 01_1_idv_genero.qmd
        - 01_2_idv_edad.qmd
        - 01_3_idv_ccaa.qmd
    - part: "2 · Anexo"
      chapters:
        - 99_anexo_idv.qmd
        - 99_anexo_matriz.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false     
    number-depth: 2            
    css: styles.css
    embed-resources: true
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    toc: true
    number-sections: false
    number-depth: 2
    prefer-html: true
    self-contained: true
    include-in-header:
      - cover-style.tex
    include-before-body:
      - cover.tex
    keep-tex: true

execute:
  freeze: auto
  warning: false
  message: false

prefer-html: true
editor: visual