---
title: "Libro de Consultas"
subtitle: "Tendencias electorales (varias encuestas)"
format:
  html: default
  pdf:
    include-in-header: cover-style.tex
    keep-tex: true
---

```{=latex}
\thispagestyle{empty}
\pagenumbering{gobble}
\pagecolor{coverblue}
\color{coverwhite}

\vspace*{\fill}
\begin{center}
{\robotoMedium\fontsize{36}{42}\selectfont Libro de Consultas}\\[1.5em]
{\robotoRegular\fontsize{22}{28}\selectfont Tendencias electorales (varias encuestas)}\\[2em]
{\robotoLight\fontsize{18}{24}\selectfont Eliseo}\\[2em]
\today
\end{center}
\vspace*{\fill}

\pagecolor{white}
\pagenumbering{arabic}
\clearpage
```

# Introducción

En este documento se presentan gráficos y resumenes de diferentes variables relacionadas con el comportamiento electoral con respecto a las próximas elecciones generales.<br> Los datos proceden de diferentes fuentes que ponen a disposición del público sus datos, sobre todo CIS y 40db, pero también Sigma Dos, Sociométrica, Opina360 etc.

El documento consta de la siguientes variables:

-   **Intención de voto**: Intención de voto a los principales partidos entre la población general y en función de diferentes variables sociodemográficas.
-   **Transferencias**: Porcentaje de votantes fieles y de fugas a otros partidos, a la abstención o que se encuentran indecisos
-   **Variación:** Variación en puntos porcentuales de la IDV a los principales partidos con respecto a septiembre de 2023
